{
 "title": "IAM Service Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(jvm_memory_used_bytes, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Application Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"$service\"} * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "JVM Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"$service\", area=\"heap\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Traffic & Performance (RED Method)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Throughput (Requests / sec)",
   "type": "timeseries",
   "description": "Requests per second (Exemplars enabled - click the dots!)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(http_server_requests_milliseconds_count{job=\"$service\"}[1m])",
     "legendFormat": "{{uri}} ({{method}})"
    }
   ]
  },
  {
   "title": "Latency (Avg Response Time)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(rate(http_server_requests_milliseconds_sum{job=\"$service\"}[1m]) / rate(http_server_requests_milliseconds_count{job=\"$service\"}[1m])) / 1000",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}